# Generated by Django 5.0.2 on 2024-03-05 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="cant",
            field=models.TextField(blank=True),
        ),
    ]
